### ISSUE TITLE
fix bad rule submitted by user (me) for "Dog Collars" mod

### ISSUE THREAD

**Issue by slippycheeze** [rimpy-custom/communityRules#411]
Apparently I not only screwed up and initially created the rule to load "Dog Collars" *before* "VFE Vikings", I managed to submit that version.  It should have been a "loadAfter" rule, like all the others.  Relevant bit is here:

```
		"shenanigans.dogcollars": {
			"loadBefore": {
				"oskarpotocki.vfe.vikings": {
					"name": ["Vanilla Factions Expanded - Vikings"],
					"comment": ["XML patches applied to VFE Vikings content; see manifest.xml in collars for evidence."]
				}
			},
```

Please be kind and fix this so I don't continue to die of shame.

**Comment by rimpy-custom** [comment]
Thank you for report, will be fixed!
