### ISSUE TITLE
Suggestion - Dealing with 'UNKNOWN' after removing mod with DDS textres

### ISSUE THREAD

**Issue by quianalevitt** [rimpy-custom/communityRules#416]
I noticed today when cleaning up some old mods I decided to drop that after reloading, the DDS textures were left behind, causing RimPY to notice the mod folder, but label it as 'UNKNOWN' in bright red.  Recommend an error-handling clause.  Potentially by prompting the user at boot to 'Remove 'UNKNOWN' empty mod folders with DDS?' Yes/No type prompt.  This alerts to the user to why the UNKNOWN mods may be there, and what they are while giving them a choice to remove them if they're done with the ones, or leave them if they may be redownloading/troubleshooting things.

**Comment by rimpy-custom** [comment]
Wrong repository, sorry
