### ISSUE TITLE
Rules from brucethemoose

### ISSUE THREAD

**Issue by brucethemoose** [rimpy-custom/communityRules#565]
```
{
	"maaxar.dubsskylights.tmaterialsglass.patch": {
		"name": [],
		"code": [],
		"loadAfter": {
			"dubwise.dubsskylights": {
				"name": ["Dubs Skylights"],
				"comment": ["Fixes red loading errors"],
				"sent": 27774632
			},
			"carnap2.tmaterials.glass": {
				"name": ["TMaterials - Glass"],
				"comment": ["Fixes red loading errors"],
				"sent": 27774632
			}
		},
		"loadBefore": {}
	}
}
```

**Comment by brucethemoose** [comment]
Oh I didn't mean for my loadbottom rules to be submitted.

Nevertheless, docworld and perf optimizer are obvious late loaders.

**Comment by miguelvitta** [comment]
late loaders is something that should be used sparingly. Dues to how patching works, I actually have to worry more about other patches interfering with mine than the mods being patched being above mine.

**Comment by rimpy-custom** [comment]
Modified rulepack to exclude load bottoms.
